application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      adobeappbuilder:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: info
            annotations:
              require-adobe-auth: true
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: info
              apiKey: $API_KEY
              providerId: $PROVIDER_ID
              eventCode: $EVENT_CODE
            annotations:
              require-adobe-auth: true
              final: true
          commerce:
            function: actions/commerce/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: info
              COMMERCE_URL: $COMMERCE_URL
              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
            annotations:
              require-adobe-auth: true
              final: true
