application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      adobeappbuilder:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              apiKey: 5d745aaeb364422b8459878afdd9ab76
              providerId: 71893478-b36b-4bc9-8f88-1f43680be6b4
              eventCode: com.postman.productsold
            annotations:
              require-adobe-auth: false
              final: true
          commerce:
            function: actions/commerce/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
              COMMERCE_URL: $COMMERCE_URL
              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
            annotations:
              require-adobe-auth: true
              final: true
